print("day 1 - String Manipulation")
print("String Concatenation is done with the + sign.")
print('String Concatenation is done with the "+" sign')
print('e.g. print("Hello " + "World")')
print("New lines can be created with a backslash and n.")